---
version: '3.9'
services:
  develop:
    image: bupt2docker/develop:gpu
    volumes:
      - "./:/root/DataFlow"
    command: [ "/usr/bin/tail", "-f", "/dev/null" ]
    working_dir: "/root/DataFlow"
    privileged: true
    #depends_on:
    #  - hdfs-ci
    networks:
      - test

networks:
  # 本地测试网络
  test: {}
